<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sic_address"
 *
 * Auto generated by Extension Builder 2016-06-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'sic_address',
	'description' => 'Adressverwaltung',
	'category' => 'plugin',
	'author' => 'SICOR DEVTEAM',
	'author_email' => 'dev@sicor-kdl.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);