routeEnhancers:
  SicAddress:
    type: Extbase
    extension: SicAddress
    plugin: sicaddress
    routes:
      - routePath: 'atoz/{atoz}'
        _controller: 'Address::search'
        _arguments:
          atoz: 'atoz'
      - routePath: 'page/{page}'
        _controller: 'Address::list'
        _arguments:
          page: '@widget_0/currentPage'
      - routePath: 'page/{page}/atoz/{atoz}'
        _controller: 'Address::search'
        _arguments:
          page: '@widget_0/currentPage'
          atoz: 'atoz'
    defaultController: 'Address::list'
    defaults:
      page: '0'
    aspects:
      atoz:
        type: StaticRangeMapper
        start: 'A'
        end: 'Z'
      page:
        type: StaticRangeMapper
        start: '1'
        end: '200'
  SicAddressDetail:
    type: Extbase
    extension: SicAddress
    plugin: sicaddress
    routes:
      -
        routePath: '/{address_title}'
        _controller: 'Address::show'
        _arguments:
          address_title: address
    defaultController: 'Address::show'
    aspects:
      address_title:
        type: PersistedAliasMapper
        tableName: tt_address
        routeFieldName: slug
