services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SICOR\SicAddress\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  SICOR\SicAddress\EventListener\ExtensionManagerListener:
    tags:
     - name: event.listener
       method: handleEvent
       identifier: 'sicorExtensionsActivated'

